. /data/adb/modules/elvina/menu/custom_animation_and_duration_scale.sh
. /data/adb/modules/elvina/menu/custom_display_size.sh
. /data/adb/modules/elvina/menu/custom_dns.sh
. /data/adb/modules/elvina/menu/custom_fps.sh
. /data/adb/modules/elvina/menu/custom_fstrim_interval.sh
. /data/adb/modules/elvina/menu/custom_hold_delay.sh
. /data/adb/modules/elvina/menu/custom_render.sh
. /data/adb/modules/elvina/menu/custom_settings.sh
. /data/adb/modules/elvina/menu/enable_disable_app.sh
. /data/adb/modules/elvina/menu/fullscreen_immersive_getsure.sh
. /data/adb/modules/elvina/menu/game_driver.sh
. /data/adb/modules/elvina/menu/game_overlay_downscale.sh
. /data/adb/modules/elvina/menu/game_overlay_fps.sh
. /data/adb/modules/elvina/menu/game_performance.sh
. /data/adb/modules/elvina/menu/night_mode.sh
. /data/adb/modules/elvina/menu/tweak.sh
. /data/adb/modules/elvina/menu/doze_tweak.sh
. /data/adb/modules/elvina/menu/downscale.sh
. /data/adb/modules/elvina/menu/monolith.sh
. /data/adb/modules/elvina/menu/cachie.sh
. /data/adb/modules/elvina/menu/swap.sh